<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\AutoMail.Application\AutoMail.Application.csproj" />
        <ProjectReference Include="..\..\AutoMail.Infrastructure\AutoMail.Infrastructure.csproj" />
        <ProjectReference Include="..\AutoMail.Web.Client\AutoMail.Web.Client.csproj"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.2"/>
    </ItemGroup>

</Project>
